---
- name: set facts for jenkins
  set_fact: jenkins_host_dir=/srv/services/jenkins

- name: create directories for jenkins
  file: path="{{ item }}" state=directory mode=0777
  with_items:
    - "{{ jenkins_host_dir }}"
    - "{{ jenkins_data_dir }}"
    - "{{ jenkins_tmp_dir }}"

- name: create a symbolic link for jenkins data directory
  file: src="{{ jenkins_data_dir }}" dest="{{ jenkins_host_dir }}/data" state=link

- name: create a symbolic link for jenkins tmp directory
  file: src="{{ jenkins_tmp_dir }}" dest="{{ jenkins_host_dir }}/tmp" state=link

- name: start jenkins
  docker_container:
    name: jenkins
    state: started
    restart_policy: on-failure
    image: jenkins:2.19.4
    network_mode: host
    log_driver: json-file
    env:
      JENKINS_OPTS: "--httpPort={{ jenkins_ui_port }}"
      JENKINS_SLAVE_AGENT_PORT: "{{ jenkins_intercom_port }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/sys:/sys"
      - "/proc:/host/proc:ro"
      - "{{ jenkins_host_dir }}/tmp:/tmp"
      - "{{ jenkins_host_dir }}/data:/var/jenkins_home"
